### ISSUE TITLE
Going to need special logic for LWM.DeepStorage again

### ISSUE THREAD

**Issue by lilwhitemouse** [hooap/SatisfiedStorage#5]
If you like, I can do a pull request (I think there's an even faster way to do it), but as it is, Satisfied Storage won't work with Deep Storage once I start checking for mass limits again...

**Comment by burak-aydin** [comment]
a pull request would be great

**Comment by lilwhitemouse** [comment]
So sorry, been away for a bit.  I will get it to you as soon as I can!
